# You may have to change the following lines if your CUDA installation is not located in /opt/cuda or if you are using a 32 bit system.
CUDA_INCLUDE_DIR=-I/opt/cuda/include
CUDA_LIB_DIR=-L/opt/cuda/lib64

# You may have to change the following lines if the nvidia CUDA compiler (nvcc) is not in your $PATH.
NVCC=nvcc

# This is a workaround for broken nvcc/g++-4.4 compatibility.
NVCC_FLAGS=--compiler-bindir=/usr/bin/g++-4.3

# Directory to put autogenerated CUDA kernels:
CUDA_KERNEL_TMP_DIR=/tmp

# Compiler and linker:
CXX=g++
LD=g++

# Necessary CUDA libraries:
CUDA_LIBS=-lcuda -lcudart -lcublas

# Additional #defines:
DEF=-DREUSE_KERNELS

COMPILE=$(CXX) $(CUDA_INCLUDE_DIR) -DNVCC=\"$(NVCC)\" -DNVCC_FLAGS=\"$(NVCC_FLAGS)\" -DCUDA_KERNEL_TMP_DIR=\"$(CUDA_KERNEL_TMP_DIR)\" -c -O2 $(DEF)
LINK=$(LD) $(CUDA_LIB_DIR) $(CUDA_LIBS)

TARGET=test

.PHONY: all clean

all: $(TARGET)

$(TARGET): main.o cudavec.o
	$(LINK) -o $@ $^

%.o: %.cpp
	$(COMPILE) -o $@ $^

clean:
	@rm -rf *.o *~ $(TARGET)

